spring: 
  profiles: 
    include: cloud
#  datasource:
#    url: jdbc:postgresql://db.estimator.cloud:5432/cloud_estimator_aws_dev
#    username: ddharna
#    password: "Passw0rd!"
    
#  jpa:
#    properties:
#      hibernate:
#        temp: 
#          use_jdbc_metadata_defaults: false