spring:  
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud-estimator
    username: postgres
    password: "{cipher}5db65212ef51d3dec0ec5e108cf6a6b7a5517fdab8b9fd6087759da5a3f92b97"
    
  jpa:
    properties:
      hibernate:
        temp: 
          use_jdbc_metadata_defaults: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKASERVER_URI:http://localhost:8761/eureka}
