spring: 
  profiles: 
    include: cloud
  datasource:
    url: jdbc:postgresql://localhost:5432/account
    username: postgres
    password: "{cipher}5db65212ef51d3dec0ec5e108cf6a6b7a5517fdab8b9fd6087759da5a3f92b97"
    
  jpa:
    properties:
      hibernate:
        temp: 
          use_jdbc_metadata_defaults: false